version: '2'

volumes:
  adaptdata:
  adaptdb:

services:
  db:
    container_name: adaptdb
    image: mongo
    volumes:
      - adaptdb:/data/db
    # ports:
    #   - 27017:27017
  authoring:
    container_name: adaptauthoring
    image: mattwilmott/adaptauthoring:0.6.0
    volumes:
      - adaptdata:/adapt_authoring
    # build: .
    command: node server
    links:
      - db
    # depends_on:
    #   - db
    ports:
      - "5000:5000"
