version: '2'

volumes:
  adaptdata:
    external:
      name: dockeradaptauthoring_adaptdata

services:
  setup:
    # build: .
    image: mattwilmott/adaptauthoring:0.6.0
    container_name: adaptauthoring
    # extends:
    #   file: docker-compose.yml
    #   service: authoring
    # volumes_from:
    #   - adaptauthoring
    volumes:
      - adaptdata:/adapt_authoring
    external_links:
      - adaptdb
    command: node install --install Y --serverPort 5000 --serverName localhost --dbHost adaptdb --dbName adapt-tenant-master --dbUser '' --dbPass '' --dbType mongo --dbPort 27017 --root /adapt-authoring --dataRoot data --sessionSecret your-session-secret --useffmpeg Y --useSmtp false --smtpService dummy --smtpUsername smtpUser --smtpPassword smtpPass --fromAddress you@example.com --name master --displayName Master --email admin@example.com --password password --authoringToolRepository https://github.com/adaptlearning/adapt_authoring.git --frameworkRepository https://github.com/adaptlearning/adapt_framework.git --frameworkRevision 'tags/v3.3.0' --auth local --masterTenantName Master --masterTenantID 01
  upgrade:
    extends:
      service: setup
    command: node upgrade --Y/n Y

    #--email ${ADMIN_EMAIL:-admin@example.com} --password ${ADMIN_PASSWORD:-password}
